# GENERATED by ondrift/cloud .github/workflows/release.yml — do not edit.
# Hand edits survive only until the next release overwrites this file.
class Drift < Formula
  desc "CLI for Drift — the European serverless platform"
  homepage "https://ondrift.eu"
  version "0.6.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/ondrift/cloud/releases/download/cli%2Fv0.6.0/drift_v0.6.0_darwin_arm64.tar.gz"
      sha256 "b195186e7dd807f2eb8478b8f85118708d56c4946af5096e92104c586329a3d1"
    end
    on_intel do
      url "https://github.com/ondrift/cloud/releases/download/cli%2Fv0.6.0/drift_v0.6.0_darwin_amd64.tar.gz"
      sha256 "21ba6d225039520f94816f0e59d2c2acfed5393a1d56c3b854ace24f6a41ed4d"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ondrift/cloud/releases/download/cli%2Fv0.6.0/drift_v0.6.0_linux_arm64.tar.gz"
      sha256 "6cbd806564307f522cdc4b773479dfcb6a39a21c71e3482c08432b38c97b7063"
    end
    on_intel do
      url "https://github.com/ondrift/cloud/releases/download/cli%2Fv0.6.0/drift_v0.6.0_linux_amd64.tar.gz"
      sha256 "d5bfeb113fbf2db7aab2f54bb1182ce347fff0c6ac791be7f793ed7f2507be71"
    end
  end

  def install
    bin.install "drift"
  end

  test do
    assert_match "drift v0.6.0", shell_output("#{bin}/drift --version")
  end
end
